steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=REVISION_ID=${REVISION_ID}'
      - '--tag=${_IMAGE_NAME}:${TAG_NAME}'
      - '--tag=${_IMAGE_NAME}:latest'
      - '--file=./build/Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_NAME}:${TAG_NAME}'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'application-frontend'
      - '--image=${_IMAGE_NAME}:${TAG_NAME}'
      - '--region=asia-east1'
      - '--platform=managed'
images:
  - ${_IMAGE_NAME}:${TAG_NAME}
  - ${_IMAGE_NAME}:latest
substitutions:
  _IMAGE_NAME: 'asia-east1-docker.pkg.dev/${PROJECT_ID}/frontend-repo/application-frontend'
options:
  dynamic_substitutions: true
timeout: 1200s
