name: Build and Deploy to Cloud Run

on:
  create:
    tags:
      - v*

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Info
        run: gcloud info

      - name: Build and Deploy
        run: |-
          gcloud builds submit \
            --config cloudbuild.yaml \
            --substitutions=REVISION_ID=${GITHUB_SHA},TAG_NAME=$(git describe --tags)
