name: Build Beta Image to Artifact Registry

on:
  push:
    branches:
      - 'beta/**'

jobs:
  setup-build-beta:
    name: Setup and Build Beta
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Info
        run: gcloud info

      - name: Build and Deploy
        run: |-
          gcloud builds submit \
            --config cloud-build-beta.yml \
            --substitutions=REVISION_ID=${GITHUB_SHA},TAG_NAME=${GITHUB_REF_NAME//\//\-}
