name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - release*

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '370.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Info
        run: gcloud info

      - name: Build and Deploy
        run: |-
          gcloud builds submit \
            --config cloudbuild.yaml \
            --substitutions=REVISION_ID=${GITHUB_SHA}
